### ISSUE TITLE
Docker container for slurm version 20.02.5

### ISSUE THREAD

**Issue by BurnerJ** [vsoch/sview-docker#1]
I'm running centos 8 with slurm version 20.02.5, and we would really appreciate a docker container to run sview for slurm version 20.02.5. If @vsoch could build one for us, it would be greatly appreciated!

**Comment by vsoch** [comment]
Any reason you can’t give this a try yourself?

**Comment by BurnerJ** [comment]
I tried this earlier this morning, but during building I ran into an error at the following point:

Making install in html
make[2]: Entering directory `/usr/local/src/slurm/doc/html'
`dirname accounting.shtml`/shtml2html.py 20.02 accounting.shtml
/usr/bin/env: python3: No such file or directory
make[2]: *** [accounting.html] Error 127
make[2]: Leaving directory `/usr/local/src/slurm/doc/html'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/usr/local/src/slurm/doc'
make: *** [install-recursive] Error 1
Error: error building at STEP "RUN set -x     && wget -O slurm.tar.bz2 "$SLURM_DOWNLOAD_URL"     && mkdir /usr/local/src/slurm     && tar jxf slurm.tar.bz2 -C /usr/local/src/slurm --strip-components=1     && rm slurm.tar.bz2     && cd /usr/local/src/slurm     && ./configure --enable-debug --prefix=/usr --sysconfdir=/etc/slurm         --with-mysql_config=/usr/bin  --libdir=/usr/lib64     && make install     && install -D -m644 etc/cgroup.conf.example /etc/slurm/cgroup.conf.example     && install -D -m644 etc/slurm.conf.example /etc/slurm/slurm.conf.example     && install -D -m644 etc/slurm.epilog.clean /etc/slurm/slurm.epilog.clean     && install -D -m644 etc/slurmdbd.conf.example /etc/slurm/slurmdbd.conf.example     && install -D -m644 contribs/slurm_completion_help/slurm_completion.sh /etc/profile.d/slurm_completion.sh     && cd     && rm -rf /usr/local/src/slurm     && mkdir /etc/sysconfig/slurm         /var/spool/slurmd         /var/run/slurmd         /var/run/slurmdbd         /var/lib/slurmd         /var/log/slurm         /data     && touch /var/lib/slurmd/node_state         /var/lib/slurmd/front_end_state         /var/lib/slurmd/job_state         /var/lib/slurmd/resv_state         /var/lib/slurmd/trigger_state         /var/lib/slurmd/assoc_mgr_state         /var/lib/slurmd/assoc_usage         /var/lib/slurmd/qos_usage         /var/lib/slurmd/fed_mgr_state     && chown -R slurm:slurm /var/*/slurm*     && /sbin/create-munge-key": error while running runtime: exit status 2

I had noticed that the readme specified that requesting a build for a particular slurm version was an option, so I figured I would ask instead of troubleshooting further. If this is possible, it would be very appreciated, but not a problem otherwise.

**Comment by vsoch** [comment]
Gotcha, I'm glad to help if you tried and are having trouble!

**Comment by vsoch** [comment]
Can you share your version of the Dockerfile?

**Comment by BurnerJ** [comment]
Thanks! Sure, here's a txt file of the Dockerfile I'm using.

[Dockerfile.txt](https://github.com/vsoch/sview-docker/files/6124440/Dockerfile.txt)

**Comment by vsoch** [comment]
Thanks! I can help after work today or tomorrow.

**Comment by BurnerJ** [comment]
Awesome, very appreciated

**Comment by vsoch** [comment]
Here you go! This worked for me - but of course I haven't tested it on a cluster with the matching slurm. If you want to test, tell me of any issues that we can debug, I can look into them. And if it works I can add the Dockerfile to the repo for an updated version.

```dockerfile
FROM centos:7

# docker build -t vanessa/sview .

ARG SLURM_VERSION=20.02.5
ENV SLURM_DOWNLOAD_URL=https://download.schedmd.com/slurm/slurm-${SLURM_VERSION}.tar.bz2
ARG GOSU_VERSION=1.10

RUN yum makecache fast \
    && yum -y install epel-release \
    && yum -y install \
           wget \
           gtk2.0 \
           bzip2 \
           perl \
           gcc \
           gcc-c++\
           vim-enhanced \
           git \
           make \
           munge \
           munge-devel \
           python-devel \
           python-pip \
           python3 \
           python3-devel \
           python3-pip \
           mariadb-server \
           mariadb-devel \
           psmisc \
           bash-completion \
    && yum clean all \
    && rm -rf /var/cache/yum

RUN pip install Cython nose \
    && pip install Cython nose

RUN set -x \
    && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-amd64" \
#    && wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-amd64" \
#    && export GNUPGHOME="$(mktemp -d)" \
#    && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
#    && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
#    && rm -rf $GNUPGHOME /usr/local/bin/gosu.asc \
    && chmod +x /usr/local/bin/gosu \
    && gosu nobody true

RUN groupadd -r slurm --gid=995 && useradd -r -g slurm --uid=995 slurm

RUN yum -y install gtk2-devel
RUN set -x \
    && wget -O slurm.tar.bz2 "$SLURM_DOWNLOAD_URL" \
    && mkdir /usr/local/src/slurm \
    && tar jxf slurm.tar.bz2 -C /usr/local/src/slurm --strip-components=1 \
    && rm slurm.tar.bz2 \
    && cd /usr/local/src/slurm \
    && ./configure --enable-debug --prefix=/usr --sysconfdir=/etc/slurm \
        --with-mysql_config=/usr/bin --libdir=/usr/lib64 \
    && make install \
    && install -D -m644 etc/cgroup.conf.example /etc/slurm/cgroup.conf.example \
    && install -D -m644 etc/slurm.conf.example /etc/slurm/slurm.conf.example \
    && install -D -m644 etc/slurmdbd.conf.example /etc/slurm/slurmdbd.conf.example \
    && install -D -m644 contribs/slurm_completion_help/slurm_completion.sh /etc/profile.d/slurm_completion.sh \
    && cd \
    && rm -rf /usr/local/src/slurm \
    && mkdir -p /etc/sysconfig/slurm \
        /var/spool/slurmd \
        /var/run/slurmd \
        /var/run/slurmdbd \
        /var/lib/slurmd \
        /var/log/slurm \
        /data \
    && touch /var/lib/slurmd/node_state \
        /var/lib/slurmd/front_end_state \
        /var/lib/slurmd/job_state \
        /var/lib/slurmd/resv_state \
        /var/lib/slurmd/trigger_state \
        /var/lib/slurmd/assoc_mgr_state \
        /var/lib/slurmd/assoc_usage \
        /var/lib/slurmd/qos_usage \
        /var/lib/slurmd/fed_mgr_state \
    && chown -R slurm:slurm /var/*/slurm* \
    && /sbin/create-munge-key

ENTRYPOINT ["sview"]
```

**Comment by BurnerJ** [comment]
Thank you so much, works great!

**Comment by vsoch** [comment]
Sure thing! Added to the repo for future folks -> https://github.com/vsoch/sview-docker/blob/master/Dockerfile.centos7.slurm-20.02.5.

**Comment by vsoch** [comment]
I'm going to close the issue, please ping if anything else comes up.
